"""Emit a proof's claims as LaTeX, from the same objects the proof checks.

The point is that nothing is transcribed. A paper that restates a derivation by hand can drift
from the code that verifies it -- a sign flips, an index moves, and both the prose and the test
keep passing because they no longer describe the same thing. Here the expression that gets
differentiated, the expression claimed equal to it, and the expression typeset are one object,
so the document cannot disagree with the proof that backs it.

Each script builds a :class:`Proof`, registers claims on it, and writes a ``.tex`` fragment the
papers ``\\input``. A claim is a residual asserted to be zero; the fragment records both the
residual and what it was formed from.
"""

from pathlib import Path

import sympy as sp

#: Written into every generated file, so a reader who finds one in isolation knows what it is.
BANNER = (
    "% Generated by cbmr-proofs. Do not edit.\n"
    "% Every expression below is rendered from the object sympy verified, not transcribed.\n"
)


def _is_zero(residual):
    """Whether a residual closed, for scalars and every matrix flavour sympy returns.

    The flavours differ in which predicate they carry. A ``ZeroMatrix`` from the matrix-symbol
    algebra exposes ``is_ZeroMatrix`` but no ``is_zero_matrix``, and comparing it to the integer
    ``0`` is False -- so a naive check reports a mismatch on a residual that is identically the
    zero matrix. An explicit ``Matrix`` carries ``is_zero_matrix`` instead, and a scalar carries
    neither. All three are asked in turn.
    """
    if getattr(residual, "is_ZeroMatrix", False):
        return True
    zero_matrix = getattr(residual, "is_zero_matrix", None)
    if zero_matrix is not None:
        return bool(zero_matrix)
    if isinstance(residual, sp.MatrixBase):
        return all(entry == 0 for entry in residual)
    return residual == 0


class Proof:
    """A named group of claims, each a residual asserted to vanish."""

    def __init__(self, name, title, preamble=""):
        self.name, self.title, self.preamble = name, title, preamble
        self.claims = []
        self.definitions = []

    def define(self, symbol, expression, description=""):
        """Record a named expression to typeset, without asserting anything about it."""
        self.definitions.append((symbol, expression, description))
        return expression

    def claim(self, label, residual, detail=""):
        """Assert a residual is zero, print the outcome, and record it for the fragment."""
        closed = _is_zero(residual)
        self.claims.append((label, residual, closed, detail))
        status = "0  exact" if closed else f"MISMATCH: {residual}"
        print(f"   {label:58s} {status}")
        return closed

    @property
    def closed(self):
        """Whether every claim vanished."""
        return all(c[2] for c in self.claims)

    def write(self, directory="docs/generated"):
        """Write the LaTeX fragment for this proof."""
        path = Path(directory) / f"{self.name}.tex"
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [BANNER, f"\\subsection{{{self.title}}}\n"]
        if self.preamble:
            lines.append(self.preamble.strip() + "\n")

        if self.definitions:
            lines.append("\n\\noindent The expressions the claims are formed from:\n")
            for symbol, expression, description in self.definitions:
                lines.append("\\begin{equation*}")
                lines.append(f"  {symbol} = {sp.latex(expression)}")
                lines.append("\\end{equation*}")
                if description:
                    lines.append(f"\\noindent {description}\n")

        lines.append("\n\\noindent Residuals, each asserted to vanish:\n")
        lines.append("\\begin{center}\\small")
        lines.append("\\begin{tabular}{lll}")
        lines.append("\\toprule")
        lines.append("claim & residual & result\\\\")
        lines.append("\\midrule")
        for label, residual, closed, detail in self.claims:
            shown = detail if detail else "\\text{(see above)}"
            mark = "$0$" if closed else "\\textbf{MISMATCH}"
            lines.append(f"{_escape(label)} & ${shown}$ & {mark}\\\\")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{center}\n")
        verdict = "every residual is exactly zero" if self.closed else "AT LEAST ONE CLAIM FAILED"
        lines.append(f"\\noindent\\textbf{{Verdict:}} {verdict}.\n")
        path.write_text("\n".join(lines))
        print(f"   -> wrote {path}")
        return path


def _escape(text):
    """Escape the LaTeX specials that appear in these labels."""
    for old, new in [("_", r"\_"), ("^", r"\^{}"), ("%", r"\%"), ("&", r"\&")]:
        text = text.replace(old, new)
    return text
